package Project2;

import static Project2.DBhandler.updateExistingMof;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Abd Al-Massih
 */
public class Mofadala extends javax.swing.JFrame {

    JTextField[] mofMarksSci = new JTextField[10];
    JTextField[] mofMarksLit = new JTextField[10];

    WelcomeFrame w;

    public Mofadala(WelcomeFrame wf, String s) {
        setLocationRelativeTo(null);

//        wf.setEnabled(false);
//        mofYearTextField.requestFocus();
//        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        initComponents();
        pack();
        setVisible(true);
        helloLabel.setText("Hello, " + s + ". Please enter the minimum total mark for each college:");

        ButtonGroup bg = new ButtonGroup();
        bg.add(sciMofRadioButton);
        bg.add(litMofRadioButton);

        sciMofRadioButton.setSelected(true);

        mofMarksSci[0] = mathMof;
        mofMarksSci[1] = mathMofTotal;
        mofMarksSci[2] = physicsMof;
        mofMarksSci[3] = physicsMofTotal;
        mofMarksSci[4] = chemistryMof;
        mofMarksSci[5] = chemistryMofTotal;
        mofMarksSci[6] = naturalMof;
        mofMarksSci[7] = naturalScienceMofTotal;
        mofMarksSci[8] = medicineMof;
        mofMarksSci[9] = medicineMofTotal;

        mofMarksLit[0] = arabicMof;
        mofMarksLit[1] = arabicMofTotal;
        mofMarksLit[2] = englishMof;
        mofMarksLit[3] = englishMofTotal;
        mofMarksLit[4] = historyMof;
        mofMarksLit[5] = historyMofTotal;
        mofMarksLit[6] = geographyMof;
        mofMarksLit[7] = geographyMofTotal;
        mofMarksLit[8] = fineArtsMof;
        mofMarksLit[9] = fineArtsMofTotal;

        for (int i = 0; i < mofMarksLit.length; i++) {
            mofMarksLit[i].setEnabled(false);
        }
    }

    public void clearFields() {
        for (int i = 0; i < mofMarksLit.length; i++) {
            mofMarksLit[i].setText(null);
            mofMarksSci[i].setText(null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        physicsMof = new javax.swing.JTextField();
        mathMof = new javax.swing.JTextField();
        arabicMof = new javax.swing.JTextField();
        geographyMof = new javax.swing.JTextField();
        historyMof = new javax.swing.JTextField();
        englishMof = new javax.swing.JTextField();
        naturalMof = new javax.swing.JTextField();
        chemistryMof = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        helloLabel = new javax.swing.JLabel();
        medicineMof = new javax.swing.JTextField();
        fineArtsMof = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        mathMofTotal = new javax.swing.JTextField();
        physicsMofTotal = new javax.swing.JTextField();
        chemistryMofTotal = new javax.swing.JTextField();
        naturalScienceMofTotal = new javax.swing.JTextField();
        medicineMofTotal = new javax.swing.JTextField();
        arabicMofTotal = new javax.swing.JTextField();
        englishMofTotal = new javax.swing.JTextField();
        historyMofTotal = new javax.swing.JTextField();
        fineArtsMofTotal = new javax.swing.JTextField();
        geographyMofTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        doneButton = new javax.swing.JButton();
        sciMofRadioButton = new javax.swing.JRadioButton();
        litMofRadioButton = new javax.swing.JRadioButton();
        resetButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        mofYearTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 3, true));

        physicsMof.setToolTipText("Out of 40");
        physicsMof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                physicsMofActionPerformed(evt);
            }
        });

        mathMof.setToolTipText("Out of 60");
        mathMof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathMofActionPerformed(evt);
            }
        });

        arabicMof.setToolTipText("Out of 40");
        arabicMof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arabicMofActionPerformed(evt);
            }
        });

        geographyMof.setToolTipText("Out of 40");

        historyMof.setToolTipText("Out of 30");

        englishMof.setToolTipText("Out of 30");

        naturalMof.setToolTipText("Out of 30");

        chemistryMof.setToolTipText("Out of 20");
        chemistryMof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chemistryMofActionPerformed(evt);
            }
        });

        jLabel6.setText("Math:");

        jLabel7.setText("English:");

        jLabel8.setText("Arabic:");

        jLabel9.setText("Physics:");

        jLabel10.setText("History:");

        jLabel11.setText("Chemistry:");

        jLabel13.setText("Natural Science:");

        jLabel14.setText("Geography:");

        helloLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        helloLabel.setText("Please enter the minimum total mark for each college:");

        medicineMof.setToolTipText("Out of 30");

        fineArtsMof.setToolTipText("Out of 30");

        jLabel15.setText("Medicine:");

        jLabel17.setText("Fine Arts:");

        mathMofTotal.setToolTipText("Out of 150");
        mathMofTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathMofTotalActionPerformed(evt);
            }
        });

        physicsMofTotal.setToolTipText("Out of 150");
        physicsMofTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                physicsMofTotalActionPerformed(evt);
            }
        });

        chemistryMofTotal.setToolTipText("Out of 150");
        chemistryMofTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chemistryMofTotalActionPerformed(evt);
            }
        });

        naturalScienceMofTotal.setToolTipText("Out of 150");
        naturalScienceMofTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naturalScienceMofTotalActionPerformed(evt);
            }
        });

        medicineMofTotal.setToolTipText("Out of 150");
        medicineMofTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineMofTotalActionPerformed(evt);
            }
        });

        arabicMofTotal.setToolTipText("Out of 140");
        arabicMofTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arabicMofTotalActionPerformed(evt);
            }
        });

        englishMofTotal.setToolTipText("Out of 140");
        englishMofTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishMofTotalActionPerformed(evt);
            }
        });

        historyMofTotal.setToolTipText("Out of 140");
        historyMofTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyMofTotalActionPerformed(evt);
            }
        });

        fineArtsMofTotal.setToolTipText("Out of 140");
        fineArtsMofTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fineArtsMofTotalActionPerformed(evt);
            }
        });

        geographyMofTotal.setToolTipText("Out of 140");
        geographyMofTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geographyMofTotalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Major Mark");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Total Mark");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Major Mark");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Total Mark");

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        sciMofRadioButton.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        sciMofRadioButton.setForeground(new java.awt.Color(255, 102, 102));
        sciMofRadioButton.setText("Scientific");
        sciMofRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sciMofRadioButtonActionPerformed(evt);
            }
        });

        litMofRadioButton.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        litMofRadioButton.setForeground(new java.awt.Color(255, 102, 102));
        litMofRadioButton.setText("Literary");
        litMofRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                litMofRadioButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset Marks");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Mof Year:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(194, 194, 194)
                                .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(chemistryMof, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(physicsMof, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(mathMof, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(naturalMof, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(medicineMof, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(naturalScienceMofTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(mathMofTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(chemistryMofTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(physicsMofTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(medicineMofTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel2)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(121, 121, 121)
                                        .addComponent(sciMofRadioButton)
                                        .addGap(36, 36, 36)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(geographyMof, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(fineArtsMof, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(arabicMof, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(englishMof, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(historyMof, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(geographyMofTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(historyMofTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(englishMofTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(arabicMofTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fineArtsMofTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(litMofRadioButton)
                                        .addGap(41, 41, 41)))))
                        .addGap(36, 36, 36))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(helloLabel)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mofYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(helloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(mofYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sciMofRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mathMof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(mathMofTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(physicsMof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(physicsMofTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chemistryMof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(chemistryMofTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(naturalMof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(naturalScienceMofTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(medicineMof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(medicineMofTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(litMofRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(arabicMof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(arabicMofTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(englishMof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(englishMofTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(historyMof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(historyMofTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(geographyMof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(geographyMofTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fineArtsMof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(fineArtsMofTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(resetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        //        boolean success = false;
//        do {

        mofMarksSci[0] = mathMof;
        mofMarksSci[1] = mathMofTotal;
        mofMarksSci[2] = physicsMof;
        mofMarksSci[3] = physicsMofTotal;
        mofMarksSci[4] = chemistryMof;
        mofMarksSci[5] = chemistryMofTotal;
        mofMarksSci[6] = naturalMof;
        mofMarksSci[7] = naturalScienceMofTotal;
        mofMarksSci[8] = medicineMof;
        mofMarksSci[9] = medicineMofTotal;

        mofMarksLit[0] = arabicMof;
        mofMarksLit[1] = arabicMofTotal;
        mofMarksLit[2] = englishMof;
        mofMarksLit[3] = englishMofTotal;
        mofMarksLit[4] = historyMof;
        mofMarksLit[5] = historyMofTotal;
        mofMarksLit[6] = geographyMof;
        mofMarksLit[7] = geographyMofTotal;
        mofMarksLit[8] = fineArtsMof;
        mofMarksLit[9] = fineArtsMofTotal;

        boolean noNullMarks = true;
        boolean allIntegerMarks = true;
        boolean inRangeValues = true;

        if (!mofYearTextField.getText().matches("[1-2][0-9][0-9][0-9]")) {
            JOptionPane.showMessageDialog(rootPane, "Please enter a 4-digit date for the YEAR field!");
            return;
        } else if (Integer.parseInt(mofYearTextField.getText()) < 1990 || Integer.parseInt(mofYearTextField.getText()) > 2050) {
            JOptionPane.showMessageDialog(rootPane, "Please enter a valid Mofadala date between 1990 and 2050.");
            return;
        }

        if (sciMofRadioButton.isSelected()) {

            for (int j = 0; j < mofMarksSci.length; j++) {
                if (mofMarksSci[j].getText().equalsIgnoreCase("") || mofMarksSci[j].getText() == null) {
                    noNullMarks = false;
                    JOptionPane.showMessageDialog(rootPane, "There are EMPTY mark fields, please fill them!", "Input Error", JOptionPane.ERROR_MESSAGE);
                    break;
                }
            }

            if (noNullMarks) {

                for (int j = 0; j < mofMarksSci.length; j++) {
                    if (!mofMarksSci[j].getText().matches("[+-]?\\d+")) {
                        allIntegerMarks = false;
                        JOptionPane.showMessageDialog(rootPane, "Some mark fields have NON-INTEGER values('" + mofMarksSci[j].getText() + "'), please recheck them!");
                        break;
                    }
                }
                if (allIntegerMarks) {
//                    try {

                    for (int i = 0; i < mofMarksSci.length; i++) {
                        if (Integer.parseInt(mofMarksSci[i].getText()) < 0) {
                            inRangeValues = false;
                            JOptionPane.showMessageDialog(rootPane, "Can't input NEGATIVE marks! ('" + mofMarksSci[i].getText() + "')");
                            break;
                        } else if (Integer.parseInt(mofMarksSci[i].getText()) > Integer.parseInt(mofMarksSci[i].getToolTipText().split("\\s+")[2])) {
                            inRangeValues = false;
                            JOptionPane.showMessageDialog(rootPane, "You cannot input marks GREATER than the TOTAL MARK! ('" + mofMarksSci[i].getText() + "')");
                            break;

                        }

                    }
                    if (inRangeValues) {
                        if (DBhandler.mofYearExists(this)) {
                            int ss = JOptionPane.showConfirmDialog(null, "The Mofadala year you entered already exists, do you want to replace it?");
                            if (ss == 0) {
                                updateExistingMof(this, Integer.parseInt(this.getMofYearTextField().getText()));
                                JOptionPane.showMessageDialog(null, "Successfully updated Scientific Mofadala!");
                                this.setVisible(false);
                            }

                        } else {
                            DBhandler.insertMof(this);
                            JOptionPane.showMessageDialog(null, "Successfully inserted Scientific Mofadala!");
                            this.setVisible(false);
                        }
                    }
                }
            }
        } else if (litMofRadioButton.isSelected()) {

            for (int j = 0; j < mofMarksLit.length; j++) {
                if (mofMarksLit[j].getText().equalsIgnoreCase("") || mofMarksLit[j].getText() == null) {
                    noNullMarks = false;
                    JOptionPane.showMessageDialog(rootPane, "There are EMPTY mark fields, please fill them!", "Input Error", JOptionPane.ERROR_MESSAGE);
                    break;
                }
            }

            if (noNullMarks) {

                for (int j = 0; j < mofMarksLit.length; j++) {
                    if (!mofMarksLit[j].getText().matches("[+-]?\\d+")) {
                        allIntegerMarks = false;
                        JOptionPane.showMessageDialog(rootPane, "Some mark fields have NON-INTEGER values ('" + mofMarksLit[j].getText() + "'), please recheck them!");
                        break;
                    }
                }
                if (allIntegerMarks) {
//                    try {

                    for (int i = 0; i < mofMarksLit.length; i++) {
                        if (Integer.parseInt(mofMarksLit[i].getText()) < 0) {
                            JOptionPane.showMessageDialog(rootPane, "Can't input NEGATIVE marks! ('" + mofMarksLit[i].getText() + "'");
                            break;
                        } else if (Integer.parseInt(mofMarksLit[i].getText()) > Integer.parseInt(mofMarksLit[i].getToolTipText().split("\\s+")[2])) {
                            inRangeValues = false;
                            JOptionPane.showMessageDialog(rootPane, "Can't input marks GREATER than the TOTAL MARK! ('" + mofMarksLit[i].getText() + "'");
                            break;

                        }

//                success = true;
                    }
                    if (inRangeValues) {

                        DBhandler.updateExistingMof(this, 2017);
                        JOptionPane.showMessageDialog(null, "Successfully updated Literary Mofadala!");
                        this.setVisible(false);
                    }
//                    } catch (Exception e) {
//                        JOptionPane.showMessageDialog(rootPane, "Invalid characters, please re-enter your Mofadala!");
//
////                     new Mofadala().setVisible(true);
//                    }

//                this.setVisible(false);
                    // TODO add your handling code here:
                }
            }
        }
    }//GEN-LAST:event_doneButtonActionPerformed

    private void arabicMofTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arabicMofTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arabicMofTotalActionPerformed

    private void medicineMofTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineMofTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineMofTotalActionPerformed

    private void naturalScienceMofTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naturalScienceMofTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_naturalScienceMofTotalActionPerformed

    private void chemistryMofTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chemistryMofTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chemistryMofTotalActionPerformed

    private void physicsMofTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physicsMofTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_physicsMofTotalActionPerformed

    private void mathMofTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathMofTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mathMofTotalActionPerformed

    private void chemistryMofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chemistryMofActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chemistryMofActionPerformed

    private void arabicMofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arabicMofActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arabicMofActionPerformed

    private void mathMofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathMofActionPerformed

        mathMof.setToolTipText("Out of 40");        // TODO add your handling code here:
    }//GEN-LAST:event_mathMofActionPerformed

    private void physicsMofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physicsMofActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_physicsMofActionPerformed

    private void englishMofTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishMofTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_englishMofTotalActionPerformed

    private void historyMofTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyMofTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historyMofTotalActionPerformed

    private void fineArtsMofTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fineArtsMofTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fineArtsMofTotalActionPerformed

    private void geographyMofTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geographyMofTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_geographyMofTotalActionPerformed

    private void sciMofRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sciMofRadioButtonActionPerformed
        for (int i = 0; i < mofMarksLit.length; i++) {
            mofMarksLit[i].setEnabled(false);
        }
        for (int i = 0; i < mofMarksSci.length; i++) {
            mofMarksSci[i].setEnabled(true);
        }
    }//GEN-LAST:event_sciMofRadioButtonActionPerformed

    private void litMofRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_litMofRadioButtonActionPerformed
        for (int i = 0; i < mofMarksSci.length; i++) {
            mofMarksSci[i].setEnabled(false);
        }
        for (int i = 0; i < mofMarksLit.length; i++) {
            mofMarksLit[i].setEnabled(true);
        }
    }//GEN-LAST:event_litMofRadioButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        clearFields();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mofadala.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mofadala.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mofadala.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mofadala.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Mofadala mof = new Mofadala(new WelcomeFrame(), "");
                mof.setVisible(true);

                //   System.out.println(mof.mathMof.getToolTipText().split(" ")[2]+2);
            }
        });
    }
    public JTextField[] getMofMarksSci() {
        return mofMarksSci;
    }

    public JTextField[] getMofMarksLit() {
        return mofMarksLit;
    }

    public JTextField getArabicMof() {
        return arabicMof;
    }

    public JTextField getArabicMofTotal() {
        return arabicMofTotal;
    }

    public JButton getCancelButton() {
        return cancelButton;
    }

    public JTextField getChemistryMof() {
        return chemistryMof;
    }

    public JTextField getChemistryMofTotal() {
        return chemistryMofTotal;
    }

    public JButton getDoneButton() {
        return doneButton;
    }

    public JTextField getEnglishMof() {
        return englishMof;
    }

    public JTextField getEnglishMofTotal() {
        return englishMofTotal;
    }

    public JTextField getFineArtsMof() {
        return fineArtsMof;
    }

    public JTextField getFineArtsMofTotal() {
        return fineArtsMofTotal;
    }

    public JTextField getGeographyMof() {
        return geographyMof;
    }

    public JTextField getGeographyMofTotal() {
        return geographyMofTotal;
    }

    public JTextField getHistoryMof() {
        return historyMof;
    }

    public JTextField getHistoryMofTotal() {
        return historyMofTotal;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public JLabel getjLabel13() {
        return jLabel13;
    }

    public JLabel getjLabel14() {
        return jLabel14;
    }

    public JLabel getjLabel15() {
        return jLabel15;
    }

    public JLabel getjLabel16() {
        return helloLabel;
    }

    public JLabel getjLabel17() {
        return jLabel17;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JRadioButton getLitMofRadioButton() {
        return litMofRadioButton;
    }

    public JTextField getMathMof() {
        return mathMof;
    }

    public WelcomeFrame getW() {
        return w;
    }

    public JTextField getMathMofTotal() {
        return mathMofTotal;
    }

    public JTextField getMedicineMof() {
        return medicineMof;
    }

    public JTextField getMedicineMofTotal() {
        return medicineMofTotal;
    }

    public JTextField getNaturalMof() {
        return naturalMof;
    }

    public JTextField getNaturalScienceMofTotal() {
        return naturalScienceMofTotal;
    }

    public JTextField getPhysicsMof() {
        return physicsMof;
    }

    public JTextField getPhysicsMofTotal() {
        return physicsMofTotal;
    }

    public JButton getResetButton() {
        return resetButton;
    }

    public JRadioButton getSciMofRadioButton() {
        return sciMofRadioButton;
    }

    public JLabel getHelloLabel() {
        return helloLabel;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public JTextField getMofYearTextField() {
        return mofYearTextField;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField arabicMof;
    public javax.swing.JTextField arabicMofTotal;
    private javax.swing.JButton cancelButton;
    public javax.swing.JTextField chemistryMof;
    public javax.swing.JTextField chemistryMofTotal;
    public javax.swing.JButton doneButton;
    public javax.swing.JTextField englishMof;
    public javax.swing.JTextField englishMofTotal;
    public javax.swing.JTextField fineArtsMof;
    public javax.swing.JTextField fineArtsMofTotal;
    public javax.swing.JTextField geographyMof;
    public javax.swing.JTextField geographyMofTotal;
    private javax.swing.JLabel helloLabel;
    public javax.swing.JTextField historyMof;
    public javax.swing.JTextField historyMofTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton litMofRadioButton;
    public javax.swing.JTextField mathMof;
    public javax.swing.JTextField mathMofTotal;
    public javax.swing.JTextField medicineMof;
    public javax.swing.JTextField medicineMofTotal;
    private javax.swing.JTextField mofYearTextField;
    public javax.swing.JTextField naturalMof;
    public javax.swing.JTextField naturalScienceMofTotal;
    public javax.swing.JTextField physicsMof;
    public javax.swing.JTextField physicsMofTotal;
    private javax.swing.JButton resetButton;
    private javax.swing.JRadioButton sciMofRadioButton;
    // End of variables declaration//GEN-END:variables
}
